### ISSUE TITLE
No such file or directory './hashable_general_v1.pkl'

### ISSUE THREAD

**Issue by jaypantone** [AnonGit90210/RamanujanMachine#1]
I tried setting up as instructed on both Mac and Linux, and in both cases get the following error message:

```
Traceback (most recent call last):
  File "main.py", line 211, in <module>
    main()
  File "main.py", line 95, in main
    with open(params.hashtable_file, 'rb') as input_file:
FileNotFoundError: [Errno 2] No such file or directory: './hashtable_general_v1.pkl'
```

**Comment by gillhofer** [comment]
file: `config.ini`:
``
hashtable_file_operation=generate
``

**Comment by jaypantone** [comment]
Thanks, this fixed it!
