### ISSUE TITLE
can not run it

### ISSUE THREAD

**Issue by ruchid123123** [AnonGit90210/RamanujanMachine#23]
Traceback (most recent call last):
  File "/home/ubuntu/RamanujanMachine-master/main.py", line 3, in <module>
    import enum_params
  File "/home/ubuntu/RamanujanMachine-master/enum_params.py", line 6, in <module>
    import cont_fracs
  File "/home/ubuntu/RamanujanMachine-master/cont_fracs.py", line 3, in <module>
    import basic_representation_types
  File "/home/ubuntu/RamanujanMachine-master/basic_representation_types.py", line 4, in <module>
    from mpmath import ln
ModuleNotFoundError: No module named 'mpmath'

**Comment by ruchid123123** [comment]
after install math , 

  File "/home/ubuntu/.local/lib/python3.10/site-packages/mpmath/ctx_mp_python.py", line 79, in __new__
    v._mpf_ = mpf_pos(cls.mpf_convert_arg(val, prec, rounding), prec, rounding)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/mpmath/ctx_mp_python.py", line 86, in mpf_convert_arg
    if isinstance(x, basestring): return from_str(x, prec, rounding)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/mpmath/libmp/libmpf.py", line 1331, in from_str
    man, exp = str_to_man_exp(x, base=10)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/mpmath/libmp/libmpf.py", line 1308, in str_to_man_exp
    x = MPZ(int(x, base))
ValueError: Exceeds the limit (4300) for integer string conversion: value has 100000 digits; use sys.set_int_max_str_digits() to increase the limit
